version: "3.3"

services:
  webapp:
    image: rivollierg/guilosore
    ports:
      - 5010:5010
    links:
      - db
      - model
    command: ["siteweb"]
  
  db:
    image: postgres
    restart: always
    volumes:
      - ../WYM_project/DBB/persistanceDB:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=wym_admin
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432

  model:
    image: quay.io/codait/max-text-summarizer
    ports: 
      - 5000:5000

  monitor:
    image: rivollierg/guilosore-monitor
    ports:
      - 8501:8501
    links:
      - db
    command: [/app/monitor/monitoring.py]