version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ../data/WYM_project/DBB/persistanceDB:/var/lib/postgresql/data
    ports:
      - 5432:5432	 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=wym_admin
      - POSTGRES_PASSWORD=admin
